[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express", "pdf-parse"]
  node_bundler = "esbuild"

[[headers]]
  for = "/pdf.worker.min.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
