import { Link } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FileText } from "lucide-react";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-muted/20">
      <div className="container mx-auto px-4 py-16 max-w-4xl">
        <div className="mb-8">
          <Link to="/" className="text-primary hover:underline">
            ← Back to Home
          </Link>
        </div>

        <div className="flex items-center gap-3 mb-6">
          <FileText className="w-10 h-10 text-primary" />
          <h1 className="text-4xl font-bold">Terms of Service</h1>
        </div>

        <p className="text-muted-foreground mb-8">
          Last Updated: {new Date().toLocaleDateString()}
        </p>

        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>1. Acceptance of Terms</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                By accessing or using our AI Interview Practice Platform ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Service.
              </p>
              <p className="mt-4">
                These Terms constitute a legally binding agreement between you and our platform. We reserve the right to modify these Terms at any time, and your continued use of the Service constitutes acceptance of any changes.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>2. Description of Service</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                Our platform provides AI-powered interview practice and career development tools, including:
              </p>
              <ul>
                <li>Simulated interview sessions with AI-generated questions</li>
                <li>Real-time speech recognition and analysis</li>
                <li>Performance evaluation and feedback</li>
                <li>Resume building and optimization tools</li>
                <li>Career mentoring and guidance</li>
              </ul>
              <p className="mt-4">
                <strong>Important:</strong> Our Service is designed as a practice and educational tool only. It does not guarantee employment outcomes or interview success. The feedback provided is generated by AI and should be used as guidance, not as definitive career advice.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>3. User Accounts and Eligibility</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <h4 className="font-semibold mt-4">3.1 Eligibility</h4>
              <p>
                You must be at least 16 years old to use this Service. By creating an account, you represent that you meet this age requirement and that all information you provide is accurate and complete.
              </p>

              <h4 className="font-semibold mt-4">3.2 Account Security</h4>
              <p>
                You are responsible for:
              </p>
              <ul>
                <li>Maintaining the confidentiality of your account credentials</li>
                <li>All activities that occur under your account</li>
                <li>Notifying us immediately of any unauthorized access</li>
                <li>Ensuring your account information remains accurate and up-to-date</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>4. Acceptable Use Policy</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>You agree NOT to:</p>
              <ul>
                <li>Use the Service for any illegal or unauthorized purpose</li>
                <li>Violate any laws in your jurisdiction</li>
                <li>Attempt to gain unauthorized access to the platform or other users' accounts</li>
                <li>Interfere with or disrupt the Service or servers</li>
                <li>Upload or transmit malicious code, viruses, or harmful content</li>
                <li>Scrape, data mine, or extract data using automated means without permission</li>
                <li>Reverse engineer, decompile, or disassemble any part of the Service</li>
                <li>Impersonate others or provide false information</li>
                <li>Use the Service to harass, abuse, or harm others</li>
                <li>Resell or commercially exploit the Service without authorization</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>5. Content and Intellectual Property</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <h4 className="font-semibold mt-4">5.1 Your Content</h4>
              <p>
                You retain ownership of content you submit (resumes, responses, etc.). By using the Service, you grant us a limited license to use, store, and process your content solely to provide and improve the Service.
              </p>

              <h4 className="font-semibold mt-4">5.2 Our Intellectual Property</h4>
              <p>
                All content, features, and functionality of the Service (including but not limited to text, graphics, logos, software, AI models) are owned by us or our licensors and are protected by intellectual property laws.
              </p>

              <h4 className="font-semibold mt-4">5.3 Feedback</h4>
              <p>
                Any feedback, suggestions, or ideas you provide may be used by us without obligation or compensation to you.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>6. Privacy and Data Protection</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                Your use of the Service is also governed by our <Link to="/privacy-policy" className="text-primary hover:underline">Privacy Policy</Link>, which describes how we collect, use, and protect your personal information. Please review it carefully.
              </p>
              <p className="mt-4">
                <strong>Audio and Video:</strong> When you participate in interview sessions, audio recordings may be processed for speech recognition and evaluation. Video (if enabled) is processed locally unless you explicitly save sessions.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>7. Subscription and Payment Terms</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <h4 className="font-semibold mt-4">7.1 Free and Paid Services</h4>
              <p>
                We offer both free and paid subscription tiers. Premium features require a paid subscription.
              </p>

              <h4 className="font-semibold mt-4">7.2 Billing</h4>
              <ul>
                <li>Subscription fees are billed in advance on a recurring basis</li>
                <li>You authorize us to charge your payment method</li>
                <li>Prices may change with 30 days' notice</li>
                <li>All fees are non-refundable except as required by law</li>
              </ul>

              <h4 className="font-semibold mt-4">7.3 Cancellation</h4>
              <p>
                You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>8. Disclaimers and Limitations</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <h4 className="font-semibold mt-4">8.1 Service Availability</h4>
              <p>
                The Service is provided "as is" and "as available." We do not guarantee uninterrupted, error-free, or secure operation. We may modify, suspend, or discontinue any part of the Service at any time.
              </p>

              <h4 className="font-semibold mt-4">8.2 AI-Generated Content</h4>
              <p>
                Our Service uses artificial intelligence to generate questions, feedback, and evaluations. While we strive for accuracy and helpfulness, AI-generated content may contain errors or may not be suitable for all situations. You should use your own judgment and not rely solely on AI feedback for career decisions.
              </p>

              <h4 className="font-semibold mt-4">8.3 No Guarantee of Results</h4>
              <p>
                We make no guarantees regarding employment outcomes, interview performance, or career advancement as a result of using our Service.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>9. Limitation of Liability</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from:
              </p>
              <ul>
                <li>Your use or inability to use the Service</li>
                <li>Any unauthorized access to or use of our servers</li>
                <li>Any interruption or cessation of the Service</li>
                <li>Any bugs, viruses, or harmful code transmitted through the Service</li>
                <li>Any errors or omissions in content or AI-generated feedback</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>10. Indemnification</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                You agree to indemnify and hold us harmless from any claims, damages, losses, liabilities, and expenses (including legal fees) arising from:
              </p>
              <ul>
                <li>Your use of the Service</li>
                <li>Your violation of these Terms</li>
                <li>Your violation of any rights of another party</li>
                <li>Any content you submit to the Service</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>11. Termination</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                We reserve the right to suspend or terminate your account and access to the Service at any time, with or without notice, for any reason, including violation of these Terms.
              </p>
              <p className="mt-4">
                Upon termination, your right to use the Service will immediately cease. We may delete your account and content, though some data may be retained as required by law or for legitimate business purposes.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>12. Dispute Resolution</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <h4 className="font-semibold mt-4">12.1 Governing Law</h4>
              <p>
                These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which our company is registered, without regard to conflict of law principles.
              </p>

              <h4 className="font-semibold mt-4">12.2 Dispute Resolution Process</h4>
              <p>
                In the event of any dispute, you agree to first contact us to attempt to resolve the issue informally. If we cannot resolve the dispute within 30 days, either party may pursue formal dispute resolution.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>13. General Provisions</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <ul>
                <li><strong>Entire Agreement:</strong> These Terms constitute the entire agreement between you and us regarding the Service.</li>
                <li><strong>Severability:</strong> If any provision is found unenforceable, the remaining provisions remain in effect.</li>
                <li><strong>Waiver:</strong> Our failure to enforce any right or provision does not constitute a waiver.</li>
                <li><strong>Assignment:</strong> You may not assign these Terms without our consent. We may assign these Terms without restriction.</li>
                <li><strong>No Agency:</strong> No agency, partnership, or joint venture is created by these Terms.</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>14. Contact Information</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                If you have questions about these Terms of Service, please contact us:
              </p>
              <ul>
                <li>Email: legal@aiinterview.com</li>
                <li>Contact Page: <Link to="/contact" className="text-primary hover:underline">Visit our Contact page</Link></li>
              </ul>
            </CardContent>
          </Card>
        </div>

        <div className="mt-12 p-6 bg-muted/50 rounded-lg border-2 border-primary/20">
          <p className="text-sm text-muted-foreground">
            <strong>By creating an account or using the Service, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.</strong>
          </p>
        </div>
      </div>
    </div>
  );
}
