import "dotenv/config";
import express from "express";
import cors from "cors";
import { handleDemo } from "./routes/demo";
import { handleCareerMentor } from "./routes/careerMentor";
import { handleStoryTelling } from "./routes/storytelling";
import { handleContact } from "./routes/contact";
import { 
  handleStartInterview, 
  handleNextQuestion, 
  handleFinishInterview 
} from "./routes/interview";
import { handleExtractPdf } from "./routes/extractPdf";
import {
  handleGetQuestions,
  handleGetPrevYearQuestions,
  handleGetCurrentAffairs,
  handleGetLeaderboard,
  handleGetDashboard,
} from "./routes/govtExam";
import { handleTTS } from "./routes/tts";
import {
  handleGenerateAIPlan,
  handleGetStudyTemplate,
  handleGetSyllabus,
  handleGetChapterQuestions,
  handleSubmitChapterTest,
  handleAIChapterGuide,
} from "./routes/studyPlan";

export function createServer() {
  const app = express();

  // Middleware
  app.use(cors());
  app.use(express.json({ limit: "50mb" }));
  app.use(express.urlencoded({ extended: true, limit: "50mb" }));

  // Core routes
  app.get("/api/ping", (_req, res) => {
    const ping = process.env.PING_MESSAGE ?? "ping";
    res.json({ message: ping });
  });

  app.get("/api/demo", handleDemo);

  // ── AI Career Mentor ──────────────────────────────────────────────────
  // POST /api/career-mentor
  // Body: { message: string, context?: string }
  // Returns: structured advice, roadmap, salary info, resources
  // ─────────────────────────────────────────────────────────────────────
  app.post("/api/career-mentor", handleCareerMentor);

  // ── Story Telling API ─────────────────────────────────────────────────
  // POST /api/story
  // Body: { topic: string }
  // Returns: { story: string } — Bengali narrative generated by Gemini AI
  // Spoken by AWS Polly TTS on the client via /api/tts
  // ─────────────────────────────────────────────────────────────────────
  app.post("/api/story", handleStoryTelling);

  // ── Interview API ─────────────────────────────────────────────────────
  // POST /api/interview/start
  // Body: { userId: string, jobRole: string, experienceLevel: string, cvText: string }
  // Returns: { sessionId: string, firstQuestion: string, totalQuestions: number }
  // 
  // POST /api/interview/next-question
  // Body: { sessionId: string, previousAnswer?: string }
  // Returns: { question: string, questionNumber: number, totalQuestions: number, isLastQuestion: boolean }
  // 
  // POST /api/interview/finish
  // Body: { sessionId: string, lastAnswer?: string }
  // Returns: { overallScore, communicationScore, technicalScore, confidenceScore, feedback, suggestions, duration }
  // ─────────────────────────────────────────────────────────────────────
  app.post("/api/interview/start", handleStartInterview);
  app.post("/api/interview/next-question", handleNextQuestion);
  app.post("/api/interview/finish", handleFinishInterview);

  // ── Contact Form ──────────────────────────────────────────────────────
  // POST /api/contact
  // Body: { name, email, subject, category, message }
  // Sends email via SMTP to site owner + auto-reply to sender
  // ─────────────────────────────────────────────────────────────────────
  app.post("/api/contact", handleContact);

  // ── PDF Text Extraction ───────────────────────────────────────────────
  // POST /api/extract-pdf
  // Body: { data: string }  — base64-encoded PDF
  // Returns: { text: string }
  // ─────────────────────────────────────────────────────────────────────
  app.post("/api/extract-pdf", handleExtractPdf);

  // ── Government Exam Practice API ──────────────────────────────────────
  // GET /api/govt/questions?exam=&subject=&difficulty=&count=
  // GET /api/govt/prev-year-questions?exam=&year=&subject=
  // GET /api/govt/current-affairs
  // GET /api/govt/leaderboard?filter=weekly|monthly
  // GET /api/govt/dashboard
  // ─────────────────────────────────────────────────────────────────────
  app.get("/api/govt/questions", handleGetQuestions);
  app.get("/api/govt/prev-year-questions", handleGetPrevYearQuestions);
  app.get("/api/govt/current-affairs", handleGetCurrentAffairs);
  app.get("/api/govt/leaderboard", handleGetLeaderboard);
  app.get("/api/govt/dashboard", handleGetDashboard);

  // ── Text-to-Speech (AWS Polly) ────────────────────────────────────────
  // POST /api/tts
  // Body: { text: string, language?: string }
  // Returns: audio/mpeg stream
  // ─────────────────────────────────────────────────────────────────────
  app.post("/api/tts", handleTTS);

  // ── Study Plan & Syllabus API ──────────────────────────────────────────
  app.post("/api/studyplan/ai", handleGenerateAIPlan);
  app.get("/api/studyplan/template/:examId", handleGetStudyTemplate);
  app.get("/api/syllabus/:examId", handleGetSyllabus);
  app.get("/api/test/:chapterId/questions", handleGetChapterQuestions);
  app.post("/api/test/submit", handleSubmitChapterTest);
  app.post("/api/ai/chapter-guide", handleAIChapterGuide);

  return app;
}
